"""empty message

Revision ID: 3f20cb0a2a3f
Revises: ea6d11fe3926
Create Date: 2024-04-11 19:27:10.166480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f20cb0a2a3f'
down_revision = 'ea6d11fe3926'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('petition__chat', schema=None) as batch_op:
        batch_op.drop_constraint('petition__chat_user_events_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_events_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('petition__chat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_events_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('petition__chat_user_events_id_fkey', 'user', ['user_events_id'], ['id'])

    # ### end Alembic commands ###
