"""empty message

Revision ID: 604c11418339
Revises: a6703b952a2f
Create Date: 2024-04-11 19:07:54.413999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '604c11418339'
down_revision = 'a6703b952a2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('event__type')
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_type_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'event_type', ['event_type_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('event_type_id')

    op.create_table('event__type',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='event__type_pkey')
    )
    op.drop_table('event_type')
    # ### end Alembic commands ###
