"""empty message

Revision ID: 6c61675d67cf
Revises: 3f20cb0a2a3f
Create Date: 2024-04-11 19:29:21.074424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c61675d67cf'
down_revision = '3f20cb0a2a3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('petition__chat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_petition', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['id_petition'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('petition__chat', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_petition')

    # ### end Alembic commands ###
