"""empty message

Revision ID: d8062a3ca96f
Revises: 222c4a55e1bf
Create Date: 2024-04-14 15:12:40.850348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8062a3ca96f'
down_revision = '222c4a55e1bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user__profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('description', sa.String(length=500), nullable=False))
        batch_op.add_column(sa.Column('profile_image', sa.String(length=250), nullable=False))
        batch_op.drop_column('ubication')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user__profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ubication', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.drop_column('profile_image')
        batch_op.drop_column('description')
        batch_op.drop_column('location')

    # ### end Alembic commands ###
